version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000" # s3-compatible api
      - "9001:9001" # web ui
    environment:
      MINIO_ROOT_USER: helloworld
      MINIO_ROOT_PASSWORD: helloworld
    command: server --console-address ":9001" /data
